

cluster: "sbatch --job-name={rule} --output=logs/{rule}/{wildcards.sample}.out --time={resources.time} --mem={resources.mem_mb} --cpus-per-task={resources.cpus}"
jobs: 500
default-resources:
  - time=10  # Default time in minutes (adjustable per rule)
  - mem_mb=1000  # Default memory in MB
  - cpus=1  # Default number of CPUs
restart-times: 1  # Number of times to retry failed jobs
max-jobs-per-second: 10
max-status-checks-per-second: 5
latency-wait: 60  # Time to wait for job completion
